<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="fr.edjaz.socle.test.LogbackRecorderTest" tests="16" skipped="0" failures="0" errors="0" timestamp="2019-02-22T13:07:01" hostname="dev" time="0.049">
  <properties/>
  <testcase name="testTraceWithException" classname="fr.edjaz.socle.test.LogbackRecorderTest" time="0.001"/>
  <testcase name="testOff" classname="fr.edjaz.socle.test.LogbackRecorderTest" time="0.001"/>
  <testcase name="testClear" classname="fr.edjaz.socle.test.LogbackRecorderTest" time="0.0"/>
  <testcase name="testDebug" classname="fr.edjaz.socle.test.LogbackRecorderTest" time="0.001"/>
  <testcase name="testError" classname="fr.edjaz.socle.test.LogbackRecorderTest" time="0.0"/>
  <testcase name="testTrace" classname="fr.edjaz.socle.test.LogbackRecorderTest" time="0.001"/>
  <testcase name="testInfo" classname="fr.edjaz.socle.test.LogbackRecorderTest" time="0.001"/>
  <testcase name="testWarn" classname="fr.edjaz.socle.test.LogbackRecorderTest" time="0.0"/>
  <testcase name="testErrorWithException" classname="fr.edjaz.socle.test.LogbackRecorderTest" time="0.0"/>
  <testcase name="testCaptureException" classname="fr.edjaz.socle.test.LogbackRecorderTest" time="0.001"/>
  <testcase name="testInfoWithException" classname="fr.edjaz.socle.test.LogbackRecorderTest" time="0.001"/>
  <testcase name="testReleaseException" classname="fr.edjaz.socle.test.LogbackRecorderTest" time="0.001"/>
  <testcase name="testOffWithException" classname="fr.edjaz.socle.test.LogbackRecorderTest" time="0.0"/>
  <testcase name="testWarnWithException" classname="fr.edjaz.socle.test.LogbackRecorderTest" time="0.0"/>
  <testcase name="testDebugWithException" classname="fr.edjaz.socle.test.LogbackRecorderTest" time="0.001"/>
  <testcase name="testLogbackException" classname="fr.edjaz.socle.test.LogbackRecorderTest" time="0.033"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
